import TaskBoard from "@/components/boards/TaskBoard/TaskBoard";
import type { IColumns, ITasks } from "@/components/boards/types";

const initialTasks: ITasks = [
    {
        id: "1",
        title: "Task 1",
        description: "Description 1",
        status: "inProgress",
    },
    {
        id: "2",
        title: "Task 2",
        description: "Description 2",
        status: "pending",
    },
    {
        id: "3",
        title: "Task 3",
        description: "Description 3",
        status: "completed",
    },
    {
        id: "4",
        title: "Task 4",
        description: "Description 4",
        status: "inProgress",
    },
    {
        id: "5",
        title: "Task 5",
        description: "Description 5",
        status: "completed",
    },
    {
        id: "6",
        title: "Task 6",
        description: "Description 6",
        status: "pending",
    },
    {
        id: "7",
        title: "Task 7",
        description: "Description 7",
        status: "inProgress",
    },
    {
        id: "8",
        title: "Task 8",
        description: "Description 8",
        status: "completed",
    },
    {
        id: "9",
        title: "Task 9",
        description: "Description 9",
        status: "pending",
    },
    {
        id: "10",
        title: "Task 10",
        description: "Description 10",
        status: "inProgress",
    },
];

const columns: IColumns = [
    { id: "col-inProgress", title: "inProgress" },
    { id: "col-pending", title: "pending" },
    { id: "col-completed", title: "completed" },
];

// PageProps is generated by Next from the real route segments, so `params` is
// correctly typed as a Promise and renaming the folder becomes a build error.
async function BoardPage({ params }: PageProps<"/boards/[boardId]">) {
    const { boardId } = await params;

    return (
        <TaskBoard
            // Remounts the client component when you navigate to another board,
            // so its useState picks up the new server data instead of keeping
            // the previous board's tasks.
            key={boardId}
            initialTasks={initialTasks}
            boardId={boardId}
            columns={columns}
        />
    );
}

export default BoardPage;
